<?php

return [
    'channels' => [
        'google_jobs' => [
            'active' => true,
            'label' => 'Google for Jobs',
            'delivery_type' => 'pull',
            'publish_method' => 'schema',
            'auth_method' => 'none',
            'execution_mode' => 'sync',
            'phase' => 'in_scope',
            'capabilities' => [
                'schema' => true,
                'feed' => false,
                'oauth' => false,
                'api_push' => false,
                'automation_fallback' => false,
                'async_required' => false,
                'draft' => false,
                'retry' => false,
                'publish_status' => true,
            ],
        ],
        'indeed' => [
            'active' => true,
            'label' => 'Indeed',
            'delivery_type' => 'pull',
            'publish_method' => 'feed',
            'auth_method' => 'none',
            'execution_mode' => 'sync',
            'phase' => 'in_scope',
            'capabilities' => [
                'schema' => false,
                'feed' => true,
                'oauth' => false,
                'api_push' => false,
                'automation_fallback' => false,
                'async_required' => false,
                'draft' => true,
                'retry' => true,
                'publish_status' => true,
            ],
        ],
        'glassdoor' => [
            'active' => true,
            'label' => 'Glassdoor',
            'delivery_type' => 'pull',
            'publish_method' => 'feed_syndication',
            'auth_method' => 'none',
            'execution_mode' => 'sync',
            'phase' => 'in_scope',
            'capabilities' => [
                'schema' => false,
                'feed' => true,
                'oauth' => false,
                'api_push' => false,
                'automation_fallback' => false,
                'async_required' => false,
                'draft' => true,
                'retry' => true,
                'publish_status' => true,
            ],
        ],
        'linkedin' => [
            'active' => true,
            'label' => 'LinkedIn',
            'delivery_type' => 'push',
            'publish_method' => 'oauth_api',
            'auth_method' => 'oauth',
            'execution_mode' => 'async',
            'phase' => 'in_scope',
            'capabilities' => [
                'schema' => false,
                'feed' => false,
                'oauth' => true,
                'api_push' => true,
                'automation_fallback' => true,
                'async_required' => true,
                'draft' => true,
                'retry' => true,
                'publish_status' => true,
            ],
        ],
        'monster' => [
            'active' => false,
            'label' => 'Monster',
            'delivery_type' => 'deferred',
            'publish_method' => 'deferred',
            'auth_method' => 'tbd',
            'execution_mode' => 'tbd',
            'phase' => 'deferred',
            'capabilities' => [
                'schema' => false,
                'feed' => false,
                'oauth' => false,
                'api_push' => false,
                'automation_fallback' => false,
                'async_required' => false,
                'draft' => false,
                'retry' => false,
                'publish_status' => false,
            ],
        ],
    ],
    'job_board_platforms' => [
        'indeed',
        'glassdoor',
        'linkedin',
        'monster',
    ],
    'automation' => [
        'role' => (string) env('MULTIPOSTING_AUTOMATION_ROLE', 'fallback'),
        'enabled' => filter_var(env('MULTIPOSTING_AUTOMATION_ENABLED', false), FILTER_VALIDATE_BOOL),
        'platforms' => array_values(array_filter(array_map(
            static fn (string $platform): string => trim($platform),
            explode(',', (string) env('MULTIPOSTING_AUTOMATION_PLATFORMS', 'linkedin'))
        ))),
        'queue' => (string) env('MULTIPOSTING_AUTOMATION_QUEUE', 'automation'),
        'timeout_seconds' => max(30, (int) env('MULTIPOSTING_AUTOMATION_TIMEOUT_SECONDS', 180)),
        'node_binary' => (string) env('MULTIPOSTING_AUTOMATION_NODE_BINARY', 'node'),
        'script_path' => (string) env('MULTIPOSTING_AUTOMATION_SCRIPT_PATH', 'scripts/rpa/post-job.mjs'),
        'headless' => filter_var(env('MULTIPOSTING_AUTOMATION_HEADLESS', true), FILTER_VALIDATE_BOOL),
        'screenshot_dir' => (string) env('MULTIPOSTING_AUTOMATION_SCREENSHOT_DIR', 'storage/app/private/rpa_failures'),
    ],
    'api_push' => [
        'queue' => (string) env('MULTIPOSTING_API_PUSH_QUEUE', 'default'),
        'auto_after_response' => filter_var(env('MULTIPOSTING_API_PUSH_AUTO_AFTER_RESPONSE', true), FILTER_VALIDATE_BOOL),
    ],
];
